spring:
  application:
    name: customer-master-api

  # Database Configuration - MySQL local
  datasource:
    url: jdbc:mysql://localhost:3306/customer_master_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: appuser
    password: apppass
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-timeout: 20000

  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update   # dùng update cho local dev, đỡ phải tạo bảng tay
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /

# Logging Configuration
logging:
  level:
    com.example.myapp: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
